### ISSUE TITLE
repository 'node' does not exist

### ISSUE THREAD

**Issue by onmyway133** [oh-my-fish/plugin-node#5]
Hi, I run `omf install node` and get

```
Installing package node
fatal: repository 'node' does not exist
Could not install package node.
```

How to deal with this? Thanks

**Comment by Jarred-Sumner** [comment]
Copy paste the github repo into `omf install` and that will work:

```omf install https://github.com/oh-my-fish/plugin-node```

**Comment by onmyway133** [comment]
@Jarred-Sumner Hi, thanks for the suggestion. It works 🚀

**Comment by bobthecow** [comment]
Hrm. You shouldn't need to do that.

**Comment by Jarred-Sumner** [comment]
I agree but I had the same problem and that’s what worked for me :(

**Comment by bobthecow** [comment]
I think it's deprecated? Try `node-binpath` instead? It doesn't do anything with `nvm`, but it actually does the rest of what the `node` plugin does the right way.

cc @sagebind @scorphus @derekstavis thoughts?
