### ISSUE TITLE
I can't install this package

### ISSUE THREAD

**Issue by alsuga** [oh-my-fish/plugin-node#7]
The repository doesn't exists.
```
Updating https://github.com/oh-my-fish/packages-main master... Done!
Installing package node
fatal: repositorio 'node' no existe
Could not install node.
```

**Comment by sagebind** [comment]
It does indeed seem to be missing from the package index; odd. I'll add it in and then you can verify that it becomes installable.

**Comment by sagebind** [comment]
OK, fixed with this commit: https://github.com/oh-my-fish/packages-main/commit/7e330623a33ba9f086a9ab047ae7162d4fed9288

**Comment by alsuga** [comment]
Thanks!
